add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[battery]
full_symbol = " "
charging_symbol = " " 
discharging_symbol = " "

[[battery.display]]
threshold = 33
style = "bold red"

[[battery.display]]
threshold = 67
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[cmd_duration]
min_time = 500

[directory]
truncation_length = 8
truncation_symbol = ".../"
home_symbol = "~"
style = "bold cyan"

